definitions:
  models.RequestBatch:
    properties:
      correlation_id:
        type: string
      original_url:
        type: string
    type: object
  models.RequestURL:
    properties:
      url:
        type: string
    type: object
  models.ResponseBatch:
    properties:
      correlation_id:
        type: string
      short_url:
        type: string
    type: object
  models.ResponseURL:
    properties:
      result:
        type: string
    type: object
  models.UserURLs:
    properties:
      original_url:
        type: string
      short_url:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Сервис сокращения ссылок.
  title: Shortener API
  version: "1.0"
paths:
  /:
    post:
      consumes:
      - text/plain
      description: Сокращает полученную ссылку и добавляет в БД
      parameters:
      - description: Ссылка для сокращения
        in: body
        name: RequestURL
        required: true
        schema:
          type: string
      produces:
      - text/plain
      responses:
        "201":
          description: Cокращенная ссылка
          schema:
            type: string
        "500":
          description: Внутренняя ошибка
          schema:
            type: string
      summary: Добавляет ссылку
  /{id}:
    get:
      description: Перенаправляет по сокращенной ссылке на оригинальную
      parameters:
      - description: Link ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "307":
          description: Перенапралено на оригинальную ссылку
          schema:
            type: string
        "400":
          description: Ссылка не найдена
          schema:
            type: string
        "410":
          description: Ссылка удалена
          schema:
            type: string
        "500":
          description: Внутренняя ошибка
          schema:
            type: string
      summary: Перенаправляет по сокращенной ссылке на оригинальную
  /api/shorten:
    post:
      consumes:
      - application/json
      description: Сокращает полученную ссылку и добавляет в БД
      parameters:
      - description: Ссылка для сокращения
        in: body
        name: RequestURL
        required: true
        schema:
          $ref: '#/definitions/models.RequestURL'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.ResponseURL'
        "400":
          description: Неверный запрос
          schema:
            type: string
        "500":
          description: Внутренняя ошибка
          schema:
            type: string
      summary: Добавляет ссылку
  /api/shorten/batch:
    post:
      consumes:
      - application/json
      description: Сокращает полученные ссылки и добавляет в БД
      parameters:
      - description: Ссылки для сокращения
        in: body
        name: RequestURL
        required: true
        schema:
          items:
            $ref: '#/definitions/models.RequestBatch'
          type: array
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/models.ResponseBatch'
            type: array
        "400":
          description: Неверный запрос
          schema:
            type: string
        "409":
          description: Добавляемая ссылка уже существует
          schema:
            type: string
        "500":
          description: Внутренняя ошибка
          schema:
            type: string
      summary: Добавляет пакет ссылкок
  /api/user/urls:
    get:
      consumes:
      - application/json
      description: Возвращает список ссылок добавленных пользователем
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.UserURLs'
            type: array
        "204":
          description: У пользователя нет ссылок
          schema:
            type: string
        "500":
          description: Внутренняя ошибка
          schema:
            type: string
      summary: Возвращает список ссылок добавленных пользователем
    post:
      consumes:
      - application/json
      description: Возвращает список ссылок добавленных пользователем
      parameters:
      - description: ID ссылок для удаления
        in: body
        name: urlsID
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - application/json
      responses:
        "202":
          description: Запрос приянт в обработку
          schema:
            type: string
        "400":
          description: Неверный запрос
          schema:
            type: string
      summary: Удаляет ссылки пользователя по ID
  /ping:
    get:
      description: Проверка соединения с БД
      responses:
        "200":
          description: Успешное соединение
          schema:
            type: string
        "500":
          description: Внутренняя ошибка
          schema:
            type: string
      summary: Проверка соединения с БД
swagger: "2.0"
